import Head from 'next/head'
import { useRouter } from 'next/router';

export default function Home() {
  // useRouter
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center bg-slate-800">
        <p className='text-white'>
          Get started DECKMONO&nbsp;
          <code className="p-3 font-mono text-lg text-green-500 bg-gray-100 rounded-md" onClick={() => router.push('/login')}>
            Go to login
          </code>
        </p>
      </main>
    </>
  )
}
